### PR TITLE
Fixes #177 again.

### LINKED ISSUE #177: macro name is a reserved identifier
```
/home/jonesmz/meshpp_frameworks/3rdparty/ozo/include/ozo/error.h:527: warning: macro name is a reserved identifier [-Wreserved-id-macro]
        #define __OZO_SQLSTATE_NAME(value) case value: return std::string(#value) + "(" + detail::ltob36(value) + ")";
                ^
```

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by thed636** [comment]
Michael, I think this command should be helpful: `scripts/build.sh pg docker all` will run all the tests (unfortunately except MacOS) and help you to save time.

**Comment by jonesmz** [comment]
Thank you for the suggestion.

Unfortunately, I do not have the ability to run docker containers.

**Comment by thed636** [comment]
> Unfortunately, I do not have the ability to run docker containers.

That's a pity. So you can still use `scripts/build.sh all` to run builds for `gcc` and `clang` on your platform without integration tests with PostgreSQL. In case if you want to run PostgreSQL integration tests without Docker - run PostgreSQL and define the next variables:

* `POSTGRES_HOST` - if you are using something different from localhost
* `POSTGRES_DB` - database name 
* `POSTGRES_USER` - user for tests
* `POSTGRES_PASSWORD` - password for user
* `OZO_BUILD_PG_TESTS=ON` - turn on the flag to build and lunch tests.

I hope that helps you to make the process easier and more enjoyable.

**Review by thed636 — APPROVED** [review]
Fanks for the PR, it will be merged after #176

**Pull request merged**
