### PR TITLE
Fix test instructions

### PR DESCRIPTION
**Pull request by jonesmz**

### CODE REVIEW

**Comment by jonesmz** [comment]
Another change I could make a PR for is to modify

```
make -j$(nproc)
```
to
```
cmake --build . --parallel $(nproc) --verbose --clean-first
```

Which is a more idomatic way to build cmake projects.

**Review by thed636 — APPROVED** [review]

**Comment by jonesmz** [comment]
Do you want me to add another commit to change it to `cmake --build . --parallel $(nproc) --verbose --clean-first` ?

Or would you rather leave it as `make` ?

**Comment by thed636** [comment]
@jonesmz would it be nice to add it as a separate recommendation to simplify and speed up the process?

**Comment by jonesmz** [comment]
The reason someone might want "cmake --build ." is because they won't need to know anything about the generator that cmake defaulted to on the current platform.

Theres:

- Make
- MSBuild
- Ninja

and others

**Comment by thed636** [comment]
Yes, that’s a good reason, let’s add it instead of `make`.

**Comment by jonesmz** [comment]
Just to confirm you're looking to have me make a PR that adds cmake --build . --parallel $(nproc) --verbose --clean-first to the instructions?

**Comment by thed636** [comment]
Yes, sure. I just merged this PR, since it was approved.

**Pull request merged**
